### ISSUE TITLE
Uncaught TypeError: operations.forEach is not a function

### ISSUE THREAD

**Issue by sicktastic** [stimulusreflex/cable_ready#149]
I am getting this error all of a sudden, and was trying to figure it out but couldn't find any resources.  

```
Uncaught TypeError: operations.forEach is not a function
    at Object.perform (cable_ready.js:11)
    at Subscription.received (progress_controller.js:14)
    at action_cable.js:536
    at Array.map (<anonymous>)
    at Subscriptions.notify (action_cable.js:535)
    at Connection.message (action_cable.js:369)
```

The error message is referencing:

```
import { xpathToElement, dispatch } from './utils';
import activeElement from './active_element';
import OperationStore from './operation_store';
import actionCable from './action_cable';

var perform = function perform(operations) {
  var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {
    emitMissingElementWarnings: true
  };
  var batches = {};
  operations.forEach(function (operation) {
    if (!!operation.batch) batches[operation.batch] = batches[operation.batch] ? ++batches[operation.batch] : 1;
  });
  operations.forEach(function (operation) {
    var name = operation.operation;
...
...
```

Any help would be appreciated!

**Comment by leastbad** [comment]
Hey Anthony! We will get you sorted. 

First, can you tell me your exact gem and npm package versions, please?

**Comment by sicktastic** [comment]
Hey @leastbad 

Thanks! 

Gem: `cable_ready (4.5.0)`
Package: `cable_ready@^5.0.0-pre3`

It was working fine a few days ago—and I wonder if any of the updates are causing this problem. 

By the way, this project is awesome!

**Comment by leastbad** [comment]
This should be an easy fix!

https://cableready.stimulusreflex.com/v/v5/installation#upgrading-package-versions-and-sanity

Install the `5.0.0.pre3` gem and your problems should melt away.

**Comment by sicktastic** [comment]
✅  That did it!  Thank you so so so much! 💥
