### ISSUE TITLE
updates_for: add option to opt out of morphing if element is currently focused

### ISSUE THREAD

**Issue by julianrubisch** [stimulusreflex/cable_ready#160]
I've seen a lot of edge cases right now when re-applying focus didn't work as intended and work done in the meantime (entering text etc.) was lost.

this is especially annoying when the updates are triggered by another user and you lose your work.

I think we should add an option (or even make it the default?) to not morph any specific `updates_for` element that currently has focus (or one of its shadow children)

thoughts @leastbad @erlingur ?

**Comment by julianrubisch** [comment]
I think this was already fixed?

**Comment by leastbad** [comment]
> I think this was already fixed?

My memory is that SSoT is working in pre7, but there's no opt-out. In other words, it has the exact same behaviour as SR.

I *think* that we can close this.
