### ISSUE TITLE
Inlcude changed keys when broadcasting to model class? (updates_for :only)

### ISSUE THREAD

**Issue by grncdr** [stimulusreflex/cable_ready#192]
My use case is that I would like to put this in a view:

```erb
<%= updates_for StaffMember, only: 'current_task' do %>
 <%# show what people are working on #%>
<% end %>
```

That is: trigger a refresh when the `current_task` of any StaffMember changes. However, it seems like broadcasts to the subscription ID of a model class are always an empty hash, so the `:only` option is effectively ignored.

I'm pretty sure that's happening here: https://github.com/stimulusreflex/cable_ready/blob/40bc658cc500b0715dfb9fb49cf539f23f24f98c/app/models/concerns/cable_ready/updatable/model_updatable_callbacks.rb#L22-L25

Could we include the changed attributes when broadcasting to the `model.class` as well? I feel like it would at least be harmless, but maybe I've missed the reasoning for doing it this way.

**Comment by leastbad** [comment]
My understanding of line 23 is that broadcasts to the Class are specifically to respond to records being created or destroyed. The intended use case is that you have an index view, and you want to track items being added or removed from the list.

Your intention sounds perfectly reasonable to me, though.

What I suggest is that you clone the CR repo and try out what you're looking to do, and if it works, please make a PR. I'll even give you the code:
```ruby
def broadcast_update(model)
  changeset = model.respond_to?(:previous_changes) ? {changed: model.previous_changes.keys} : {}
  ActionCable.server.broadcast(model.class, changeset)
  ActionCable.server.broadcast(model.to_global_id, changeset)
end
```

**Comment by grncdr** [comment]
> My understanding of line 23 is that broadcasts to the Class are specifically to respond to records being created or destroyed.

Those are handled by `broadcast_create` (which is also aliased as `broadcast_destroy`).

> What I suggest is that you clone the CR repo and try out what you're looking to do, and if it works, please make a PR.

I actually monkey-patched this locally in my app already to test it and it works. However, I am not using CableReady very extensively so I thought I'd ask here first. I've created PR #193 with those changes.

**Comment by leastbad** [comment]
Sorry, wrt line 23 I wasn't speculating on how it works, I was speculating on the intended functionality of the feature. Apologies, that wasn't as clear as it could have been.

So really what this PR is about (since I think I already gave you the code, such as it is) is the bigger "why" question, a close cousin of "wait, does this make sense?"

I'm hoping that @julianrubisch can help me get my thoughts straight on this. Does it make sense to broadcast changed columns to the class form components? I think so, but need another pair of eyes.
