### ISSUE TITLE
CR is overriding dom_id

### ISSUE THREAD

**Issue by acetinick** [stimulusreflex/cable_ready#203]
By the recommendations we include CableReady::Broadcaster in our application controller. This then includes CableReady::Indentifable which overrides Rails provided dom_id.

This produces different results to what is expected and should be either renamed, or removed to use dom_id as Rails expected output.

**Comment by leastbad** [comment]
Rails does not provide `dom_id` to your controllers. Native `dom_id` is a helper method, intended to be used in view templates.

If you need to use Rails' native `dom_id`, please either use `ActionView::RecordIdentifier.dom_id` or remove `CableReady::Broadcaster` from your application controller.

**Comment by leastbad** [comment]
Another fix is to drop this into an initializer:
```ruby
module Turbo::FramesHelper
  def turbo_frame_tag(*ids, src: nil, target: nil, **attributes, &block)
    id = ids.map { |id| id.respond_to?(:to_key) ? ActionView::RecordIdentifier.dom_id(id) : id }.join("_")
    src = url_for(src) if src.present?

    tag.turbo_frame(**attributes.merge(id: id, src: src, target: target).compact, &block)
  end
end
```
