### ISSUE TITLE
ActiveRecord dependency breaks rspec on non AR Rails implementations

### ISSUE THREAD

**Issue by javierg** [stimulusreflex/cable_ready#207]
I have an app running with StimulusReflex ~4.x~  3.4 fine, this app have no AR whatsoever, as we use other DB which AR do not support. The migration to 5.0pre is making RSpec tests crash because AR is being required for the new identifiable feature.

I think this only happens with RSpec on test environment, as when setting eager load to true in my dev env the app works fine. 

Thanks for the awesome work!

**Comment by leastbad** [comment]
Hi, thanks for reporting.

Can you please fill in that `x` so we know what version of SR we're talking about?

It's fair to say that 100% of SR users are using `3.x`. 😉

**Comment by javierg** [comment]
Thanks for the reply, yeah there is atypo in the version number sorry about that:

The versions are:

StimulusReflex: v3.5.0.pre9
Cable Ready:  5.0.0pre9

I am testing upgrading because it was the only way to make SR work with esbuild and newer rails versions.

**Comment by leastbad** [comment]
Hey Javier, I almost replied that I thought that this issue had been fixed on master, but I realize now that @marcoroth has a branch that seems to address this but hasn't been merged.

https://github.com/stimulusreflex/cable_ready/tree/dependency-cleanup

Marco, what's the scoop on this branch?

**Comment by marcoroth** [comment]
That somehow got lost. I will bring it in a mergable state and then open a PR.

**Comment by javierg** [comment]
@marcoroth Any update on this one? Thanks

**Comment by leastbad** [comment]
I took the changes that @marcoroth made and stuck them into a PR in the hopes of getting this resolved quickly.

There's two open questions on the PR readme and also `standardrb` is currently [failing in a weird way](https://github.com/stimulusreflex/cable_ready/actions/runs/3294765236/jobs/5432607555) I don't fully grok. If you have any idea what's up there, please lmk!
