### ISSUE TITLE
Finalizer warning using Ruby 3.2.1 

### ISSUE THREAD

**Issue by ferrisoxide** [stimulusreflex/cable_ready#226]
Hi folks.

When shutting down a cable-ready app running under MRI Ruby 3.2.1 we've been getting the following warning:

> bin/rails: warning: Exception in finalizer #<Proc:0x00007f4384e74d88 ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cable_ready-4.5.0/lib/cable_ready/channel.rb:14 (lambda)>
> ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cable_ready-4.5.0/lib/cable_ready/channel.rb:14:in `block in initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)

It looks like this has only been recently introduced (see [ruby pull 3444](https://github.com/ruby/ruby/pull/3444), but harks back to an issue Mike Perham [identified back in 2010](https://www.mikeperham.com/2010/02/24/the-trouble-with-ruby-finalizers/).

We ended up monkey-patching the `CableReady::Channel` like so:

```ruby
module CableReady
  class Channel
    attr_reader :identifier, :enqueued_operations

    def initialize(identifier)
      @identifier = identifier
      reset
      CableReady.config.operation_names.each { |name| add_operation_method name }

      config_observer = self
      CableReady.config.add_observer config_observer, :add_operation_method
      ObjectSpace.define_finalizer self, self.class.finalize_observer(config_observer)
    end

    def self.finalize_observer(config_observer)
      proc { CableReady.config.delete_observer config_observer }
    end
  end
end
```

This seems to work on Ruby 3.2.1, but I've no idea if this is correct or is applicable on other Rubies. I'm not super comfortable with how ` ObjectSpace.define_finalize` works, so I'm not inclined to suggest this as a solution - just hoping it might inform someone with better chops than me.

Cheers.

**Comment by leastbad** [comment]
Thanks for the heads-up, Tom! I'm glad that you found a good solution.

There are significant changes coming down the pipe for v5, and most of the code referenced above has moved to `operation_builder.rb`, which you can find on the master branch.

If you're up for it, I'd love for you to try your app with the master branch build and see if the issue persists. @hopsoft has made several improvements to this section of the codebase over time.

**Comment by ferrisoxide** [comment]
Running the `master` branch seems to have silenced the error, but the app is now misbehaving. 

I've reverted back to using v 4.5.0 and will have to look into it later - for now the monkey patch will have to do.  

We'll have to keep our eye out for v5. Thanks @leastbad.

**Comment by leastbad** [comment]
Thanks for reporting. Any information you can provide on how the app is misbehaving will help us resolve any issues.

**Comment by leastbad** [comment]
Hey Tom, any updates on this?

I would very much love to know if and how CR 5 is breaking in your app. While there are incremental improvements, I wouldn't expect anything to explode.

If you have any stack traces, HMU with a Gist.

Otherwise, I'm going to close this issue soon, okay?

**Comment by ferrisoxide** [comment]
> Otherwise, I'm going to close this issue soon, okay?

All good. Sorry for not getting back to you, have been on holidays. We're going to be upgrading all-the-things shortly, so if we still have issues I'll raise a ticket with more background details. 

Cheers!

**Comment by leastbad** [comment]
No worries at all.

FWIW, I'm just going through all of the outstanding issues before hopefully publishing pre10 imminently. Please drop by the Discord and get my attention so that we can coordinate, as there's a brand new installer about to drop that you might want to either use or run against a `rails new` to get a diff of what we recommend for setup.

You can find out more: https://discord.com/channels/629472241427415060/1039292202221842452
