### ISSUE TITLE
Upgrading to v5.0.0.pre10 breaks Rails' named route helpers

### ISSUE THREAD

**Issue by alexander-makarenko** [stimulusreflex/cable_ready#265]
After upgrading `cable_ready` from `v5.0.0.pre9` to `v5.0.0.pre10`, lots of request and system specs in my Rails 7 application started failing. After some debugging, I realized that it was because named route helpers (e.g. `sessions_path` or `account_path(user)`) in my views started raising all sorts of weird errors, for example:

<img width="656" alt="Screenshot 2023-03-03 at 17 28 34" src="https://user-images.githubusercontent.com/28592078/222776430-50eb5491-c172-4959-89a6-d6e79b0a2264.png">

<img width="728" alt="Screenshot 2023-03-03 at 17 37 02" src="https://user-images.githubusercontent.com/28592078/222776439-7b5cede8-ac26-42b8-a01f-60aa0ea4a5ce.png">

After some further debugging (with the gem cloned locally and bundled from `/vendor`), I was able to narrow down the problem to this commit - a7c607e5a1a348837dd372bf8356b398b2b8d37a - and then this line:

https://github.com/stimulusreflex/cable_ready/blob/v5.0.0.pre10/lib/tasks/cable_ready/cable_ready.rake#L3

With that `include` commented out, all of my specs start working again as normal!

**Comment by marcoroth** [comment]
Hey @alexander-makarenko, thanks for opening this issue and sorry for the trouble it caused!

Looking at the installer, I'm not even sure why that line is even needed. I'll investigate and see if we can remove it and solve it otherwise!

**Comment by marcoroth** [comment]
Hey @alexander-makarenko, good news. We don't need the helpers anymore, and decided to remove them. It's going to be  in the next release!

Thank you! 🙏🏼

**Comment by alexander-makarenko** [comment]
Hi @marcoroth ! Thanks a lot for a quick fix, I really appreciate it.

https://github.com/stimulusreflex/cable_ready/commit/e11b123255159566c79ce5b7fad9724d9b67e438 solved it for me with CableReady, and I am now able to use it with version 3.5.0.pre9 of StimulusReflex. However, I still run into the same issue after upgrading the latter to 3.5.0.pre10, because the exact same `include` also appears [here](https://github.com/stimulusreflex/stimulus_reflex/blob/main/lib/tasks/stimulus_reflex/stimulus_reflex.rake#L3). Do you think you may be able to remove it in the StimulusReflex repo as well? Should I create a separate issue there?

**Comment by marcoroth** [comment]
Yeah, let me just remove that as well in StimulusReflex!

**Comment by marcoroth** [comment]
Just pushed up https://github.com/stimulusreflex/stimulus_reflex/commit/7607350bd25f29af2eb4eb7104bfc33958f1d058 to resolved this in StimulusReflex as well! Thanks for the feedback!

**Comment by alexander-makarenko** [comment]
Perfect! Thanks a lot for your help.
