### ISSUE TITLE
`MissingElement` is not defined on initialize

### ISSUE THREAD

**Issue by Antoine-Gerard** [stimulusreflex/cable_ready#290]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I had some issues with setting the option 'onMissingElement' to 'event' in my project today. Here are the error that I had:

>  "Uncaught ReferenceError: MissingElement is not defined"

I looked into sources to patch it in my project, and I think that the MissingElement import is missing in the "javascript/index.js" file

Thanks,
Antoine

**Comment by marcoroth** [comment]
Thank you @Antoine-Gerard, fixed in https://github.com/stimulusreflex/cable_ready/commit/059b314a3ce5dc5def08933f777e0c14cba1c91b 🙌🏼

**Comment by marcoroth** [comment]
Also just released v5.0.6 with this fix:

https://github.com/stimulusreflex/cable_ready/releases/tag/v5.0.6
