### ISSUE TITLE
Ruby 3.3 warnings about observer gem being removed from the standard library

### ISSUE THREAD

**Issue by Benjaminpjacobs** [stimulusreflex/cable_ready#293]
After upgrading to ruby 3.3.1 we are seeing the following warning:
```
/app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: /app/vendor/ruby-3.3.1/lib/ruby/3.3.0/observer.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add observer to your Gemfile or gemspec. Also contact author of cable_ready-5.0.3 to add observer into its gemspec.
```

The `observer` gem has been added to our Gemfile to quiet the warnings but are there any plans to add it to the cable_ready gemspec in upcoming releases?

**Comment by marcoroth** [comment]
Thanks for opening this issue @Benjaminpjacobs, let's add the `observer` gem to the CableReady gemspec then 👍🏼

**Comment by marcoroth** [comment]
Opened #294 to address this.
